### ISSUE TITLE
2.7.0 breaking change ?

### ISSUE THREAD

**Issue by rstoneIDBS** [bahmutov/cypress-code-coverage#38]
I've just upgraded from 2.61 to 2.7.1 (also tried 2.7.0) and this plugin now fails with the following error when running component tests:

```
  > Cannot read properties of undefined (reading 'BABEL_TYPES_8_BREAKING')

When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.

Cypress could not associate this error to any specific test.

We dynamically generated a new test to display this failure.
      at assertEach (http://localhost:5173/__cypress/src/node_modules/.vite/deps/@bahmutov_cypress-code-coverage_support.js?v=a54e7704:4989:42)
```

Reverting to 2.6.1 fixes the issue. My project currently doesn't include any babel configuration as it is Vite based and it wasn't required prior to this issue, is this something you are aware of?

**Comment by rstoneIDBS** [comment]
It seems to be related to this code  in support.js:
```
const { createInstrumenter } = require('istanbul-lib-instrument')

const instrumenter = createInstrumenter({
  esModules: true,
  compact: false,
  preserveComments: true,
})
```

If I move this down inside this code https://github.com/bahmutov/cypress-code-coverage/blob/7e5013ea7202a2e8f202aed9c2d7a5e6836f79e3/support.js#L111 then the problem no longer occurs

**Comment by bahmutov** [comment]
yeah,  might be a problematic require, let me move it
